### ISSUE TITLE
Navigated In Doesn't Work

### ISSUE THREAD

**Issue by taufiqahmed** [iShafayet/Doables#1]
### Description

navigating to another page doesn't trigger the **againNavigated** function.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by iShafayet** [comment]
Resolved in https://github.com/iShafayet/Doables/commit/750ee8fa3e738117a4fafbc59fe2de0aeb6df862
